# Ejecutar workflow al hacer push o PR en main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v3  # Clonar el repositorio

    - name: Set up Python
      uses: actions/setup-python@v4 #indica que se usará la acción oficial de GitHub para instalar Python
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -v  # Ejecutar 

        #hola
